[package]
name = "mccs-db"
version = "0.2.0" # keep in sync with README and html_root_url
authors = ["arcnmx"]
edition = "2018"

description = "MCCS specification VCP database"
keywords = ["ddc", "mccs", "vcp", "vesa"]

documentation = "https://docs.rs/mccs-db"
repository = "https://github.com/arcnmx/mccs-rs"
readme = "../README.md"
license = "MIT"

[badges]
travis-ci = { repository = "arcnmx/mccs-rs" }
maintenance = { status = "passively-maintained" }

[dependencies]
mccs = { version = "0.2", path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
nom = "3.2"

[dev-dependencies]
mccs-caps = { version = "0.2", path = "../caps" }
